### ISSUE TITLE
更新后功能失效

### ISSUE THREAD

**Issue by gilnatab** [TigerBeanst/DuolingoTimezoneFixed#1]
多邻国最近更新了新版，更新后时区修改功能就失效了，需要手动修改系统时区才能恢复国际版。

麻烦大佬更新一下插件啊。

**Comment by TigerBeanst** [comment]
哪个版本啊，我这边 Play 版的 5.90.1(1561) 是正常的……

**Comment by gilnatab** [comment]
奇怪，我的也是 Play 版的 5.90.1，但是必须修改系统时区才能有好友功能。

有什么办法导出日志给你看嘛？

我用的mix fold，安卓12

**Comment by TigerBeanst** [comment]
你要不试着注销或者重装多邻国试试？
（因为导出日志也没啥可导的……

**Comment by gilnatab** [comment]
我把多邻国卸载重装、lsp里重新启用模块、重新优化应用以后，好了。不知道哪步解决的问题....

感谢大佬。
